name: AWS_Lambda_Deploy
on:
    push:
        branches:
            - test
        # branches: [master, dev, test]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        # enviroment:
        #     name: AWS_Lambda_Deploy

        # steps:
        #     - name: Extract branch name
        #       shell: bash
        #       run: echo "::set-output"

        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: configure-aws-credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_ID }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: setup-python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"

            - name: lambda Build & update find_sync
              run: |
                  pip3 install awscli
                  mkdir -p lambda/lambda
                  mv lambda/find_sync/lambda_function.py lambda/lambda && rmdir lambda/find_sync
                  cp -r common lambda/lambda
                  cd lambda/lambda && zip -r package.zip ./*
                  aws lambda update-function-code --function-name allfree-web-api-test-find_sync --zip-file fileb://package.zip --publish

            - name: lambda Build & update update_sync
              run: |
                  pip3 install awscli
                  mv lambda/update_sync/lambda_function.py lambda/lambda && rmdir lambda/update_sync
                  cp common/* lambda/lambda
                  cd lambda/lambda && zip -r package.zip ./*
                  aws lambda update-function-code --function-name allfree-web-api-test-update_sync --zip-file fileb://package.zip --publish

            - name: lambda Build & update insert_sync
              run: |
                  pip3 install awscli
                  mv lambda/insert_sync/lambda_function.py lambda/lambda && rmdir lambda/insert_sync
                  cp -r common lambda/lambda
                  cd lambda/lambda && zip -r package.zip ./*
                  aws lambda update-function-code --function-name allfree-web-api-test-insert_sync --zip-file fileb://package.zip --publish
